/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PA;

/**
 *
 * @author HP
 */
public class icon extends javax.swing.JPanel {

    /**
     * Creates new form icon
     */
    public icon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LLAMA = new javax.swing.JPanel();
        ñ = new javax.swing.JLabel();

        LLAMA.setBackground(new java.awt.Color(255, 255, 255));

        ñ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONOS/pngwing.com.png"))); // NOI18N

        javax.swing.GroupLayout LLAMALayout = new javax.swing.GroupLayout(LLAMA);
        LLAMA.setLayout(LLAMALayout);
        LLAMALayout.setHorizontalGroup(
            LLAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LLAMALayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(ñ, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        LLAMALayout.setVerticalGroup(
            LLAMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LLAMALayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ñ, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LLAMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LLAMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LLAMA;
    private javax.swing.JLabel ñ;
    // End of variables declaration//GEN-END:variables
}
